version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: human_resource_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
