export enum ELeaveRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ELeaveType {
  ANNUAL_LEAVE = 'ANNUAL_LEAVE',
  UNPAID_LEAVE = 'UNPAID_LEAVE',
  WORK_FROM_HOME = 'WORK_FROM_HOME',
  OTHER = 'OTHER',
}
