export enum EPayrollStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
}

export const PAYROLL_SELECT = [
  'payroll.id',
  'payroll.employeeId',
  'payroll.month',
  'payroll.year',
  'payroll.basicSalary',
  'payroll.standardWorkingDays',
  'payroll.workDays',
  'payroll.leaveDays',
  'payroll.allowanceAmount',
  'payroll.bonusAmount',
  'payroll.grossSalary',
  'payroll.netSalary',
  'payroll.healthInsuranceAmount',
  'payroll.socialInsuranceAmount',
  'payroll.createdAt',
  'payroll.updatedAt',
  'employee.id',
  'employee.firstName',
  'employee.lastName',
  'employee.departmentId',
  'employee.status',
];

export const ALLOWED_SORT_FIELDS_PAYROLL = [
  'id',
  'employeeId',
  'month',
  'year',
  'basicSalary',
  'standardWorkingDays',
  'workDays',
  'allowanceAmount',
  'bonusAmount',
  'grossSalary',
  'netSalary',
  'createdAt',
  'updatedAt',
];
