export enum LeaveRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum LeaveType {
  VACATION = 'VACATION',
  SICK_LEAVE = 'SICK_LEAVE',
  PERSONAL_DAY = 'PERSONAL_DAY',
  WORK_FROM_HOME = 'WORK_FROM_HOME',
  OTHER = 'OTHER',
}
